import { Injectable, inject, signal } from '@angular/core';
import type { ProjectId, ProjectSection, Reflection, ReflectionId, SectionId } from '@cwm/contracts';
import { WORK_MANAGER_GATEWAY } from '../../../../core/gateway/work-manager-gateway';
const messageOf = (e: unknown) => e instanceof Error ? e.message : String(e);
interface ActiveRead { generation: number; promise: Promise<void>; queued: boolean; }
@Injectable()
export class ReflectionsStore {
  private readonly gateway = inject(WORK_MANAGER_GATEWAY); private generation = 0; private activeRead: ActiveRead | null = null;
  private readonly projectIdState = signal<ProjectId | null>(null); private readonly sectionIdState = signal<SectionId | null>(null); private readonly itemsState = signal<Reflection[]>([]); private readonly loadingState = signal(false); private readonly errorState = signal<string | null>(null); private readonly editingIdState = signal<ReflectionId | null>(null);
  readonly projectId = this.projectIdState.asReadonly(); readonly sectionId = this.sectionIdState.asReadonly(); readonly reflections = this.itemsState.asReadonly(); readonly items = this.reflections; readonly loading = this.loadingState.asReadonly(); readonly error = this.errorState.asReadonly(); readonly editingId = this.editingIdState.asReadonly();
  // Keyed by the section: a `reflections` container owns its rows rather than querying the
  // project's, so two of them on one canvas hold different notes.
  load(section: ProjectSection): Promise<void> { this.projectIdState.set(section.projectId); this.sectionIdState.set(section.id); return this.startRead(section, ++this.generation, false); }
  sync(section: ProjectSection): Promise<void> { if (this.sectionIdState() !== section.id || this.generation === 0) return this.load(section); if (this.activeRead?.generation === this.generation) { this.activeRead.queued = true; return this.activeRead.promise; } return this.startRead(section, this.generation, true); }
  private startRead(section: ProjectSection, generation: number, quiet: boolean): Promise<void> { const state = { generation, queued: false, promise: Promise.resolve() } as ActiveRead; if (!quiet) { this.loadingState.set(true); this.errorState.set(null); } state.promise = (async () => { try { const items = await this.gateway.reflections.list(section.projectId, { sectionId: section.id }); if (generation === this.generation && this.sectionIdState() === section.id) { this.itemsState.set([...items].sort((a,b) => b.createdAt.localeCompare(a.createdAt))); this.errorState.set(null); } } catch (e) { if (!quiet && generation === this.generation && this.sectionIdState() === section.id) { this.itemsState.set([]); this.errorState.set(messageOf(e)); } } finally { if (!quiet && generation === this.generation) this.loadingState.set(false); } })().finally(() => { if (this.activeRead !== state) return; this.activeRead = null; if (state.queued && generation === this.generation) void this.startRead(section, generation, true); }); this.activeRead = state; return state.promise; }
  async create(bodyRaw: string, titleRaw = '', prompt = ''): Promise<boolean> { const body = bodyRaw.trim(); const projectId = this.projectIdState(); const sectionId = this.sectionIdState(); if (!body || projectId === null || sectionId === null) { this.errorState.set('A reflection body is required.'); return false; } try { const created = await this.gateway.reflections.create({ projectId, sectionId, body, ...(titleRaw.trim() ? { title: titleRaw.trim() } : {}), ...(prompt ? { prompt } : {}) }); this.itemsState.update((items) => [created, ...items]); return true; } catch (e) { this.errorState.set(messageOf(e)); return false; } }
  beginEdit(id: ReflectionId) { this.editingIdState.set(id); } cancelEdit() { this.editingIdState.set(null); }
  async saveEdit(titleRaw: string, bodyRaw: string): Promise<boolean> { const id = this.editingIdState(); const body = bodyRaw.trim(); if (id === null || !body) return false; try { const updated = await this.gateway.reflections.update(id, { body, title: titleRaw.trim() || null }); this.itemsState.update((items) => items.map((item) => item.id === id ? updated : item)); this.editingIdState.set(null); return true; } catch (e) { this.errorState.set(messageOf(e)); return false; } }
  update(id: ReflectionId, bodyRaw: string, titleRaw: string) { this.editingIdState.set(id); return this.saveEdit(titleRaw, bodyRaw); }
}
