import { Injectable, inject, signal } from '@angular/core';
import type { ProjectId, Reflection, ReflectionId } from '@cwm/contracts';
import { WORK_MANAGER_GATEWAY } from '../../../../core/gateway/work-manager-gateway';
const messageOf = (e: unknown) => e instanceof Error ? e.message : String(e);
interface ActiveRead { generation: number; promise: Promise<void>; queued: boolean; }
@Injectable()
export class ReflectionsStore {
  private readonly gateway = inject(WORK_MANAGER_GATEWAY); private generation = 0; private activeRead: ActiveRead | null = null;
  private readonly projectIdState = signal<ProjectId | null>(null); private readonly itemsState = signal<Reflection[]>([]); private readonly loadingState = signal(false); private readonly errorState = signal<string | null>(null); private readonly editingIdState = signal<ReflectionId | null>(null);
  readonly projectId = this.projectIdState.asReadonly(); readonly reflections = this.itemsState.asReadonly(); readonly items = this.reflections; readonly loading = this.loadingState.asReadonly(); readonly error = this.errorState.asReadonly(); readonly editingId = this.editingIdState.asReadonly();
  load(projectId: ProjectId): Promise<void> { this.projectIdState.set(projectId); return this.startRead(projectId, ++this.generation, false); }
  sync(projectId: ProjectId): Promise<void> { if (this.projectIdState() !== projectId || this.generation === 0) return this.load(projectId); if (this.activeRead?.generation === this.generation) { this.activeRead.queued = true; return this.activeRead.promise; } return this.startRead(projectId, this.generation, true); }
  private startRead(projectId: ProjectId, generation: number, quiet: boolean): Promise<void> { const state = { generation, queued: false, promise: Promise.resolve() } as ActiveRead; if (!quiet) { this.loadingState.set(true); this.errorState.set(null); } state.promise = (async () => { try { const items = await this.gateway.reflections.list(projectId); if (generation === this.generation && this.projectIdState() === projectId) { this.itemsState.set([...items].sort((a,b) => b.createdAt.localeCompare(a.createdAt))); this.errorState.set(null); } } catch (e) { if (!quiet && generation === this.generation && this.projectIdState() === projectId) { this.itemsState.set([]); this.errorState.set(messageOf(e)); } } finally { if (!quiet && generation === this.generation) this.loadingState.set(false); } })().finally(() => { if (this.activeRead !== state) return; this.activeRead = null; if (state.queued && generation === this.generation) void this.startRead(projectId, generation, true); }); this.activeRead = state; return state.promise; }
  async create(bodyRaw: string, titleRaw = '', prompt = ''): Promise<boolean> { const body = bodyRaw.trim(); const projectId = this.projectIdState(); if (!body || projectId === null) { this.errorState.set('A reflection body is required.'); return false; } try { const created = await this.gateway.reflections.create({ projectId, body, ...(titleRaw.trim() ? { title: titleRaw.trim() } : {}), ...(prompt ? { prompt } : {}) }); this.itemsState.update((items) => [created, ...items]); return true; } catch (e) { this.errorState.set(messageOf(e)); return false; } }
  beginEdit(id: ReflectionId) { this.editingIdState.set(id); } cancelEdit() { this.editingIdState.set(null); }
  async saveEdit(titleRaw: string, bodyRaw: string): Promise<boolean> { const id = this.editingIdState(); const body = bodyRaw.trim(); if (id === null || !body) return false; try { const updated = await this.gateway.reflections.update(id, { body, title: titleRaw.trim() || null }); this.itemsState.update((items) => items.map((item) => item.id === id ? updated : item)); this.editingIdState.set(null); return true; } catch (e) { this.errorState.set(messageOf(e)); return false; } }
  update(id: ReflectionId, bodyRaw: string, titleRaw: string) { this.editingIdState.set(id); return this.saveEdit(titleRaw, bodyRaw); }
}
